version: ''

services:
  
  wordpress: 
    image: wordpress:5-php7.4-apache
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql:mysql

  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ~/Docker/wp-mysql/mysql-data:/var/lib/mysql
